Check one lock file should be there

diff --git a/.github/workflows/update-js-runtime-wrapper.yml b/.github/workflows/update-js-runtime-wrapper.yml
--- a/.github/workflows/update-js-runtime-wrapper.yml
+++ b/.github/workflows/update-js-runtime-wrapper.yml
@@ -29,6 +29,11 @@ jobs:
             exit 1
           fi
 
+          if [ ! -f yarn.lock ] && [ ! -f package-lock.json ]; then
+            echo "ERROR: No lockfile found,Policy requires exactly ONE package manager lockfile"
+            exit 1
+          fi
+
       - name: Determine Version
         id: get_version
         run: |
